language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
install:
  - composer config http-basic.repo.magento.com $MAGENTO_REPO_PUBLIC_KEY $MAGENTO_REPO_PRIVATE_KEY
  - composer install
script:
  - vendor/bin/phpunit src/Test/Unit
  - vendor/bin/phpcs --ignore=src/Test/ src/
